#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = waybar
exec-once = hyprpaper
exec-once = sunsetr
 
##########################
### AUTOSTART OPTIONAL ###
##########################

# opendeck for streamdeck
exec-once = /usr/bin/opendeck --hide
