wallpaper {
	monitor = DP-1
	path = ~/.config/hypr/wallpapers/landscape/wallpaperjwst.png
	#path = ~/.config/hypr/wallpapers/landscape/pixelcity.png
	#path = ~/.config/hypr/wallpapers/landscape/sunset.jpg
	fit_mode = cover
}

wallpaper {
	monitor = DP-2
	path = ~/.config/hypr/wallpapers/portrait/stars.png
	fit_mode = cover
}


splash = false
