hl.on("hyprland.start", function ()
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("systemctl --user start swaync")
	hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland")
	hl.exec_cmd("/usr/lib/xdg-desktop-portal-gtk")
	hl.exec_cmd("hyprctl dispatch workspace 1")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
	-- For gtk3 apps you need to install adw-gtk3 theme (sudo pacman -S adw-gtk-theme)
	hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'")

	hl.exec_cmd("sleep 1")
	hl.exec_cmd("waybar")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("sunsetr")
end)
