# Disable transparency
windowrule = match:class [fF]irefox, opaque on
windowrule = match:class [dD]iscord, opaque on
windowrule = match:class [sS]potify, opaque on

# Float
windowrule = float on, match:class [nN]emo

# Disable Rofi Animation
layerrule = match:namespace rofi, no_anim on
