# font_family JetBrainsMonoNerdFont
font_family IosevkaCustomTwo
font_size 20
cursor_shape block
shell_integration no-cursor

#include themes/nightfly-kitty.conf

cursor yellow3
background #0a0a0b

# resize running program instantly
resize_debounce_time 0 0

# prevents jiggly text due to previous line
placement_strategy top-left 
